version: '3.8'
services:
  aboard-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - .env